name: CI/CD
run-name: ${{ github.actor }} is checking CI/CD for DevOps Fundamentals ðŸš€
on: [push]
env:
  tag: ${{ secrets.DOCKER_HUB_USERNAME }}/node_js_app:latest

jobs:
  linting:
    name: Linting # job name (unique id)
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - 
        name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - 
        name: Code Checkout
        uses: actions/checkout@v2
      - 
        name: Install Dependencies
        run: npm ci
      - 
        name: Code Linting
        run: npm run lint
  BuildAndPushImage:
    runs-on: ubuntu-latest
    needs: linting
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    -
      name: Build Docker Image
      run: docker build -t ${{ env.tag }} .
    -
      name: Push Image to Docker Hub
      run: docker push ${{ env.tag }}
